name: meditation
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  lo_form: ^0.1.2
  google_fonts: ^2.1.0
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/pics/

